---
title: "Tidying ICP-MS data"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(readr)
library(janitor)
```

```{r}
#importing data
ICPMS_imported <- read.csv("~/chem313/313_icpms/data/ICPMS_Data.csv", 
                           skip = 1,
                           na = "N/A")

sample_key <- read.csv("~/chem313/313_icpms/data/Sample_Key.csv", 
                           skip = 0)


```
```{r tidying RSD data}
RSD_data <- ICPMS_imported %>%
  #renaming RSD columns with appropriate isotope name
  select(
    Cr52 = CPS.RSD,
    Cr53 = CPS.RSD.1,
    As75 = CPS.RSD.2,
    Cd111 = CPS.RSD.3,
    Cd114 = CPS.RSD.4,
    Pb208 = CPS.RSD.5,
    Ge_RSD = CPS.RSD.7,
    Sample.Key) %>%
  #gathering RSD columns and making new column to indicate which metal corresponds to which RSD
  pivot_longer(1:6, names_to = "metal", values_to = "RSD")
```

```{r tidying CPS data}
ICPMS_tidy <- ICPMS_imported %>%
  select(
    Cr52 = CPS,
    Cr53 = CPS.1,
    As75 = CPS.2,
    Cd111 = CPS.3,
    Cd114 = CPS.4,
    Pb208 = CPS.5,
    Ge72 = CPS.7,
    Sample.Key) %>%
  pivot_longer(1:6, names_to = "metal", values_to = "CPS") %>%
  #mutating in RSD data
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS = CPS/Ge72) %>%
  select(-Ge72)

#confirming that RSD data matches CPS data, output is TRUE if everything matches
all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$metal==ICPMS_tidy$metal)
```

```{r merging sample key}
ICPMS_merged <- merge(ICPMS_tidy, sample_key) %>%
  clean_names()

#ICPMS_merged 
```


```{r decluttering, warning = FALSE}
#removing everything from environment except final data set
rm(list = setdiff(ls(), "ICPMS_merged"))
```

```{r}
write.csv(ICPMS_merged, file = "~/chem313/313_icpms/data/tidy_ICPMS.csv")

```


