---
title: "ICPMS Data Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(readr)
```

```{r}
#importing the tidied ICPMS data
ICPMS <- read.csv("~/chem313/313_icpms/data/tidy_ICPMS.csv")

```

```{r}
#defining lists to be used in for loops
sample_sites <- unique(filter(ICPMS, site != "MB", site != "")$site)
#excluding method blank and quality control from list of sites
metals_analyzed <- unique(ICPMS$metal)

#preview lists to check for issues
sample_sites
metals_analyzed
```

```{r Calibration}
ICPMS_cal <- NULL
for (unique_metal in metals_analyzed) {
  #filtering for a single metal then selecting variables of interest
  cal <- ICPMS %>%
    filter(type == "Cal1" | type == "Cal2" | type == "Cal3") %>%
    filter(metal == unique_metal) %>%
    select(concentration, cps, rsd)
  #weighted linear regression
  w <- 1/(cal$cps*cal$rsd)^2
  model <- lm(cal$cps ~ cal$concentration, weights = w)
  #pulling out relevant info from model
  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope_std <- summary(model)$coefficients[2,2]
  intercept_std <- summary(model)$coefficients[1,2]
  #plotting cal curve
  plot(cal$cps ~ cal$concentration,
       xlab = paste("Concentration of ", unique_metal, "(ppb)"),
       ylab = "Counts per Second") +
    abline(model, col = "red") +
    title(paste("Calibration for ", unique_metal))
  #storing info from calibration curve
  equation <- tibble(metal = unique_metal, slope, slope_std, intercept, intercept_std)
  ICPMS_cal <- rbind(ICPMS_cal, equation)
}

ICPMS_cal
```

```{r function for sample analysis}
#inputs: unique_site (as a character)
#outputs: concentration vector

sample_analysis <- function(unique_site){
  concentration_data <- NULL
  for (unique_metal in metals_analyzed){
    sample <- filter(ICPMS, metal == unique_metal, site == unique_site)
    data <- NULL
    #iterating through each sample in unique_metal
    for (ID in sample$sample_key) {
      sample_data <- filter(sample, sample_key == ID)
      cal <- filter(ICPMS_cal, metal == unique_metal)
      #sample analysis
      m <- cal$slope
      b <- cal$intercept
      y <- sample_data$cps
      b_e <- cal$intercept_std
      m_e <- cal$slope_std
      x <- (y-b)/m #The units are dependent on the calibration standards (Kg/mL)
      RSD <- ((sample_data$rsd/100)*sample_data$cps)
      CPS <- sample_data$cps 
      #error propagation
      e_yb <- sqrt((RSD)^2 + (b_e)^2) #error in y-b from calibration
      yb <- CPS - b
      e_x <- x*sqrt((e_yb/yb)^2 +(m_e/m)^2) #error in x from calibration
      #storing data for sites that are not method blanks
      data <- rbind(data, data.frame(sample_key = ID, x, e_x))
      if (unique_site != "MB"){
        concentration_data <- data_frame(sample_key = sample_data$sample_key,
                                         analyst = sample_data$analyst,
                                         metal = unique_metal,
                                         site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
          rbind(concentration_data)
      }
    }
    if (unique_site == "MB"){
      x <- mean(data$x)
      e_x <- sd(data$x)
      concentration_data <- data_frame(metal = unique_metal,
                                       site = unique_site,
                                       conc_dil = x,
                                       conc_dil_error = e_x) %>%
        rbind(concentration_data)
    }
  }
  return(concentration_data)
}
```

```{r function for diff functions}
#inputs: a function
#outputs: a data frame with the function outputs from each site

run_sites <- function(Function){
  value <- NULL
  for (site in sample_sites){
    site_value <- Function(site)
    value <- rbind(site_value, value)
  }
  return(value)
}
```

```{r analysis}
MB <- sample_analysis("MB") #(ug/kg)
uncor_sample <- run_sites(sample_analysis) #values do not account for dilutions (ug/kg)

MB
uncor_sample
```

```{r correction and error prop}
sample_data_mb <- NULL 

for (unique_metal in metals_analyzed){
  MB_metal <- filter(MB, metal == unique_metal)
  sample_metal <- filter(uncor_sample, metal == unique_metal)
  conc_dil_blanked <- sample_metal$conc_dil - MB_metal$conc_dil
  
  #error propagation: subtraction of MB
  conc_dil_blanked_error <- sqrt((sample_metal$conc_dil_error)^2 +
                                  (MB_metal$conc_dil_error)^2)
  
  sample_data_mb <- sample_metal %>%
    mutate(conc_dil_blanked, conc_dil_blanked_error) %>%
    rbind(sample_data_mb)
}

sample_data_mb
```

```{r dilution factor}
#error propagation
vol_e <- 1
mass_e <- 0.001
dil_1010_e <- sqrt(1^2 + 10^2)
dil_e <- sqrt((dil_1010_e/1010)^2 + (1/10)^2) #error in 101 dilution factor

#correct for dilution and propagate error
sample_data <- merge(ICPMS, sample_data_mb) %>%
  unique() %>%
  mutate(conc_blanked = conc_dil_blanked*(total_volume/1000)/(mass_of_soil/1000)*101,
         conc_blanked_error = conc_blanked *   
           sqrt((conc_dil_blanked_error/conc_dil_blanked)^2 + 
           (dil_e/101)^2 +
           (mass_e/mass_of_soil)^2 +
           (vol_e/total_volume)^2),
         conc_unblanked = conc_dil*(total_volume/1000)/(mass_of_soil/1000)*101,
         conc_unblanked_error = conc_unblanked*
           sqrt((conc_dil_error/conc_dil)^2 +
                  (dil_e/101)^2 +
                  (mass_e/mass_of_soil)^2 +
                  (vol_e/total_volume)^2)) %>%
  select(-concentration,
         -type,
         -mass_of_soil,
         -total_volume,
         -cps,
         -rsd,
         -conc_dil_blanked,
         -conc_dil_blanked_error,
         -conc_dil,
         -conc_dil_error)
```

```{r cleaning environment, warning = FALSE}
rm(list = ls()[!ls() %in% c("ICPMS", "sample_data")])
```


```{r average conc from samples}
sample_conc <- sample_data %>%
  filter(site != "QC") %>%
  group_by(metal, site) %>%
  summarize(conc_mean = mean(conc_blanked),
            conc_sd = sd(conc_blanked),
            count = n()) %>%
  mutate(error = qnorm(0.975)*conc_sd/sqrt(count),
         lower = conc_mean - error,
         upper = conc_mean + error,
         mass_frac = conc_mean/1000) %>%
  select(-count,
         -error)

sample_conc_icpms <- sample_conc %>%
  filter(metal == "Cr52")

write.csv(sample_conc, "~/chem313/313_icpms/data/sample_conc_allmetals.csv")
write.csv(sample_conc_icpms, "~/chem313/313_icpms/data/sample_icpms.csv")
```

```{r average conc from qc}
qc_conc <- sample_data %>%
  filter(site == "QC") %>%
  group_by(metal) %>%
  summarize(conc_mean = mean(conc_unblanked),
            conc_sd = sd(conc_unblanked),
            count = n()) %>%
  mutate(error = qnorm(0.975)*conc_sd/sqrt(count),
         lower_ci = conc_mean - error,
         upper_ci = conc_mean + error, 
         mass_frac = conc_mean/1000,
         per_recovery = case_when(
           metal == "Cd111" | metal == "Cd114" ~ mass_frac/2.94*100,
           metal == "Cr52" | metal == "Cr53" ~ mass_frac/121.9*100,
           metal == "Pb208" ~ mass_frac/150*100
         )) %>%
  select(-count,
         -error)
```



