---
  title: "AA Data Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(readr)
```

```{r importing data}
AA <- read.csv("~/chem313/313_icpms/data/tidy_AA.csv") %>%
  mutate(rsd = as.numeric(percent_rsd)*100)
```

```{r calibration curve}
cal <- AA %>%
  filter(type != "Sample", percent_rsd != "HIGH") %>%
  select(mean_abs, rsd, concentration)
#weighted linear regression
w <- 1/(cal$mean_abs*cal$rsd)^2
model <- lm(cal$mean_abs ~ cal$concentration, weights = w)

slope <- model$coefficients[2]
intercept <- model$coefficients[1]
slope_std <- summary(model)$coefficients[2,2]
intercept_std <- summary(model)$coefficients[1,2]

plot(cal$mean_abs ~ cal$concentration,
       xlab = paste("Concentration of Cr53 (ppm)"),
       ylab = "Mean Absorbance") +
    abline(model, col = "red") +
    title(paste("Calibration for Cr53"))

equation <- tibble(metal = "Cr53", slope, slope_std, intercept, intercept_std)
cal <- rbind(equation)
cal
```

```{r}
sample_sites <- unique(filter(AA, site != "MB", site != "")$site)
#inputs: unique_site (as a character)
#outputs: concentration vector
sample_analysis <- function(unique_site){ 
#unique_site <- "A"
  concentration_data <- NULL
  sample <- filter(AA, site == unique_site)
  data <- NULL
  for (ID in sample$sample_key){
    sample_data_aa <- filter(sample, sample_key == ID)
    
    m <- cal$slope
    b <- cal$intercept
    y <- sample_data_aa$mean_abs
    
    b_e <- cal$intercept_std
    m_e <- cal$slope_std
    x <- (y-b)/m #The units are dependent on the calibration standards (Kg/mL)
    
    RSD <- ((sample_data_aa$rsd/100)*sample_data_aa$mean_abs)
    abs <- sample_data_aa$mean_abs
    #error propagation
    e_yb <- sqrt((RSD)^2 + (b_e)^2) #error in y-b from calibration
    yb <- abs - b
    e_x <- x*sqrt((e_yb/yb)^2 +(m_e/m)^2) #error in x from calibration
    data <- rbind(data, data_frame(sample_key = ID, x, e_x))
    if(unique_site != "MB"){
      concentration_data <- data_frame(sample_key = sample_data_aa$sample_key,
                                         analyst = sample_data_aa$analyst,
                                         metal = "Cr53",
                                         site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
        rbind(concentration_data)
    }
    if (unique_site == "MB"){
      x <- mean(data$x)
      e_x <- sd(data$x)
      concentration_data <- data_frame(metal = "Cr53",
                                       site = unique_site,
                                       conc_dil = x,
                                       conc_dil_error = e_x) %>%
        rbind(concentration_data)
  }
  }
  
  return(concentration_data)
}
```

```{r function for diff functions}
#inputs: a function
#outputs: a data frame with the function outputs from each site

run_sites <- function(Function){
  value <- NULL
  for (site in sample_sites){
    site_value <- Function(site)
    value <- rbind(site_value, value)
  }
  return(value)
}
```

```{r analysis}
MB <- sample_analysis("MB") #(ug/kg)
uncor_sample <- run_sites(sample_analysis) #values do not account for dilutions (ug/kg)

MB
uncor_sample
```

```{r}
sample_data_mb <- NULL
#error propagation: subtraction of MB
conc_dil_blanked <- uncor_sample$conc_dil-MB$conc_dil
conc_dil_blanked_error <- sqrt(uncor_sample$conc_dil_error)^2 + (MB$conc_dil_error)^2
sample_data_mb <- uncor_sample %>%
  mutate(conc_dil_blanked, conc_dil_blanked_error) %>%
  rbind(sample_data_mb)
sample_data_mb
```

```{r dilution factor}
#error propagation
vol_e <- 1
mass_e <- 0.001
dil_1010_e <- sqrt(1^2 + 10^2)
dil_e <- sqrt((dil_1010_e/1010)^2 + (1/10)^2) #error in 101 dilution factor

#correct for dilution and propagate error
sample_data_aa <- merge(AA, sample_data_mb) %>%
  unique() %>%
  mutate(conc_blanked = conc_dil_blanked*(total_volume/1000)/(mass_of_soil/1000),
         conc_blanked_error = conc_blanked *   
           sqrt((conc_dil_blanked_error/conc_dil_blanked)^2 + 
           (dil_e/101)^2 +
           (mass_e/mass_of_soil)^2 +
           (vol_e/total_volume)^2),
         conc_unblanked = conc_dil*(total_volume/1000)/(mass_of_soil/1000),
         conc_unblanked_error = conc_unblanked*
           sqrt((conc_dil_error/conc_dil)^2 +
                  (dil_e/101)^2 +
                  (mass_e/mass_of_soil)^2 +
                  (vol_e/total_volume)^2)) %>%
  select(-concentration,
         -type,
         -mass_of_soil,
         -total_volume,
         -rsd,
         -conc_dil_blanked,
         -conc_dil_blanked_error,
         -conc_dil,
         -conc_dil_error,
         -mean_abs,
         -percent_rsd) 
```

```{r average conc from samples}
sample_conc_aa <- sample_data_aa %>%
  filter(site != "QC") %>%
  group_by(metal, site) %>%
  summarize(conc_mean = mean(conc_blanked),
            conc_sd = sd(conc_blanked),
            count = n()) %>%
  mutate(error = qnorm(0.975)*conc_sd/sqrt(count),
         lower_ci = conc_mean - error,
         upper_ci = conc_mean + error) %>%
  select(-count,
         -error)


```


```{r average conc from qc}
qc_conc_aa <- sample_data_aa %>%
  filter(site == "QC") %>%
  group_by(metal) %>%
  summarize(conc_mean = mean(conc_unblanked),
            conc_sd = sd(conc_unblanked),
            count = n()) %>%
  mutate(error = qnorm(0.975)*conc_sd/sqrt(count),
         lower_ci = conc_mean - error,
         upper_ci = conc_mean + error, 
         mass_frac = conc_mean/1000) %>%
  select(-count,
         -error)
```

